[project]
name = "gerador-qrcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "brcode>=1.2",
    "customtkinter>=5.2.2",
    "pillow>=11.3.0",
    "pyperclip>=1.9.0",
    "qrcode[pil,svg]>=8.2",
]
